leasing/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('contract/add/', views.edit_contract, name='add_contract'),
    path('contract/<int:pk>/edit/', views.edit_contract, name='edit_contract'),
    path('contract/list/', views.list_contract, name='list_contract'),
    path('contract/<int:pk>/', views.view_contract, name='view_contract'),
    path('contract/<int:pk>/payments/', views.view_payments, name='view_payments'),

    path('payment/requested/', views.request_paid_list, name='request_paid_list'),
    path('payment/<int:pk>/request/', views.request_payment, name='request_payment'),
    path('payment/<int:pk>/<str:action>/', views.toggle_payment, name='toggle_payment_status'),

    path('warranty/list/', views.list_warranty, name='list_warranty'),
    path('warranty/add/', views.edit_warranty, name='add_warranty'),
    path('warranty/<int:pk>/edit/', views.edit_warranty, name='edit_warranty'),
    path('warranty/<int:pk>/', views.view_warranty, name='view_warranty'),
]

project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leasing.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

leasing/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from decimal import Decimal, ROUND_HALF_UP


class Profile(models.Model):
    ROLE_CHOICES = [
        ('LR', 'Lessor'),
        ('LE', 'Lessee'),
        ('SE', 'Seller'),
        ('AD', 'Admin')
    ]
    user = models.OneToOneField(
        User,
        related_name='profile',
        on_delete=models.CASCADE
    )
    display_name = models.CharField(
        max_length=200,
        blank=True,
        null=True
    )
    role = models.CharField(
        max_length=2,
        choices=ROLE_CHOICES
    )

    def __str__(self):
        return self.display_name or self.user.username


class Contract(models.Model):
    lessor = models.ForeignKey(
        User,
        related_name='lessor_contracts',
        on_delete=models.CASCADE
    )
    lessee = models.ForeignKey(
        User,
        related_name='lessee_contracts',
        on_delete=models.CASCADE
    )
    seller = models.ForeignKey(
        User,
        related_name='seller_contracts',
        on_delete=models.CASCADE
    )
    number = models.CharField(max_length=30)
    meter = models.CharField(max_length=20)
    started = models.DateField()

    class Meta:
        ordering = ['-started', '-number']

    def get_absolute_url(self):
        return reverse('view_contract', args=[self.id])

    def __str__(self):
        return self.number


class FinanceDetails(models.Model):
    contract = models.ForeignKey(
        Contract,
        related_name='finance_details',
        on_delete=models.CASCADE
    )
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    upfront = models.DecimalField(max_digits=10, decimal_places=2)
    final_payment = models.DecimalField(max_digits=10, decimal_places=2)
    period = models.PositiveIntegerField()  # in month
    rate = models.DecimalField(max_digits=6, decimal_places=2)  # in percent
    vat_rate = models.DecimalField(max_digits=6, decimal_places=2)  # in percent

    @property
    def monthly_rate(self):
        return self.rate / 1200

    @property
    def monthly_payment(self):
        payment = ((self.cost - self.upfront - self.final_payment) *
                   self.monthly_rate / (1 - (1 + self.monthly_rate) ** (-1 * self.period)) * (1 + self.vat_rate / 100))
        payment = Decimal(payment)
        payment = payment.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        return payment


class Payment(models.Model):
    contract = models.ForeignKey(
        Contract,
        related_name='payments',
        on_delete=models.CASCADE
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    paid = models.BooleanField(default=False)
    request_paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['date']


class WarrantyCase(models.Model):
    STATUS_CHOICES = [
        ('CR', 'Создан'),
        ('IW', 'В процесссе'),
        ('CO', 'Решен'),
    ]
    contract = models.ForeignKey(
        Contract,
        related_name='warranty_cases',
        on_delete=models.CASCADE
    )
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    resolved = models.CharField(
        max_length=2,
        choices=STATUS_CHOICES,
        default='CR'
    )

leasing/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import DateInput

from .models import Contract, FinanceDetails, WarrantyCase


class ContractForm(forms.ModelForm):
    class Meta:
        model = Contract
        fields = ['number', 'lessee', 'seller', 'meter', 'started']
        widgets = {
            'started': DateInput(attrs={'type': 'date', 'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['lessee'].queryset = User.objects.filter(profile__role='LE')
        self.fields['lessee'].label_from_instance = lambda obj: str(obj.profile)
        self.fields['seller'].queryset = User.objects.filter(profile__role='SE')
        self.fields['seller'].label_from_instance = lambda obj: str(obj.profile)


class FinanceDetailsForm(forms.ModelForm):
    class Meta:
        model = FinanceDetails
        fields = ['cost', 'upfront', 'final_payment', 'period', 'rate', 'vat_rate']


class WarrantyCaseForm(forms.ModelForm):
    class Meta:
        model = WarrantyCase
        fields = ['contract', 'description']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if self.user:
            self.fields['contract'].queryset = Contract.objects.filter(lessee=self.user)
            self.fields['contract'].label_from_instance = lambda obj: str(obj)

leasing/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect

from .forms import ContractForm, FinanceDetailsForm, WarrantyCaseForm
from .models import Contract, FinanceDetails, Payment, WarrantyCase
from .utils import generate_payment_dates, create_payments


@login_required
def edit_contract(request, pk=None):
    user = request.user
    company_name = user.profile.display_name
    if user.profile.role != 'LR':
        return HttpResponseForbidden("You don't have permission")
    is_new = True
    contract = None
    finance_details = None
    if pk:
        is_new = False
        contract = get_object_or_404(
            Contract,
            pk=pk,
            lessor=user,
        )
        if contract:
            finance_details = get_object_or_404(
                FinanceDetails,
                contract=contract
            )

    if request.method == 'POST':
        contract_form = ContractForm(request.POST, request.FILES, instance=contract)
        finance_details_form = FinanceDetailsForm(request.POST, instance=finance_details)

        if contract_form.is_valid() and finance_details_form.is_valid():
            contract = contract_form.save(commit=False)
            contract.lessor = user
            contract.save()

            finance_details = finance_details_form.save(commit=False)
            finance_details.contract = contract
            finance_details.save()

            payment_dates = generate_payment_dates(contract.started, finance_details.period)
            monthly_payment = finance_details.monthly_payment

            create_payments(contract, payment_dates, monthly_payment)

            return redirect('list_contract')

    contract_form = ContractForm(instance=contract)
    finance_details_form = FinanceDetailsForm(instance=finance_details)

    return render(
        request,
        'contract/edit.html',
        {
            'is_new': is_new,
            'contract_form': contract_form,
            'finance_details_form': finance_details_form,
            'company_name': company_name,
            'section': 'contract',
            'is_lessor': request.user.profile.role == 'LR',
        }
    )


@login_required
def list_contract(request):
    user = request.user
    role = user.profile.role
    is_lessor = False
    if role == 'LR':
        is_lessor = True
        contracts = Contract.objects.filter(lessor=user)
    elif role == 'LE':
        contracts = Contract.objects.filter(lessee=user)
    elif role == 'SE':
        contracts = Contract.objects.filter(seller=user)
    elif role == 'AD':
        contracts = Contract.objects.all()
    else:
        contracts = None

    return render(
        request,
        'contract/list.html',
        {
            'company_name': user.profile.display_name,
            'contracts': contracts,
            'is_lessor': is_lessor,
            'section': 'contract',
        }
    )


@login_required
def view_contract(request, pk):
    company_name = request.user.profile.display_name
    contract = get_object_or_404(Contract, pk=pk)
    finance_details = get_object_or_404(FinanceDetails, contract=contract)
    return render(
        request,
        'contract/view.html',
        {
            'contract': contract,
            'finance_details': finance_details,
            'company_name': company_name,
            'section': 'contract',
            'is_lessor': request.user.profile.role == 'LR',
        }
    )


@login_required
def view_payments(request, pk):
    is_lessor = False
    if request.user.profile.role == 'LR':
        is_lessor = True

    contract = get_object_or_404(Contract, pk=pk)
    payments = Payment.objects.filter(contract=contract)
    return render(
        request,
        'payment/view.html',
        {
            'payments': payments,
            'is_lessor': is_lessor,
            'is_lessee': request.user.profile.role == 'LE',
            'company_name': request.user.profile.display_name,
            'section': 'contract',
            'contract': contract,
        }
    )


@login_required
def toggle_payment(request, pk, action):
    payment = get_object_or_404(Payment, pk=pk)

    if request.user.profile.role == 'LR':
        if action == 'accept' and payment.request_paid and not payment.paid:
            payment.paid = True
            payment.request_paid = False
            payment.save()
        elif action == 'decline' and payment.request_paid:
            payment.request_paid = False
            payment.save()
    else:
        return HttpResponseForbidden("You are not authorized to perform this action.")

    return redirect('request_paid_list')


@login_required
def list_warranty(request):
    user = request.user
    role = user.profile.role
    is_lessee = False
    is_seller = False
    is_lessor = False

    if role == 'LR':
        is_lessor = True
        warranties = WarrantyCase.objects.filter(contract__lessor=user)
    elif role == 'LE':
        is_lessee = True
        warranties = WarrantyCase.objects.filter(contract__lessee=user)
    elif role == 'SE':
        is_seller = True
        warranties = WarrantyCase.objects.filter(contract__seller=user)
    elif role == 'AD':
        warranties = WarrantyCase.objects.all()
    else:
        warranties = None

    return render(
        request,
        'warranty/list.html',
        {
            'company_name': user.profile.display_name,
            'warranties': warranties,
            'is_lessor': is_lessor,
            'is_lessee': is_lessee,
            'is_seller': is_seller,
            'section': 'warranty',
        }
    )


@login_required
def edit_warranty(request, pk=None):
    user = request.user
    company_name = user.profile.display_name
    is_new = True
    warranty = None
    if pk:
        warranty = get_object_or_404(WarrantyCase, pk=pk)
        is_new = False

    if request.user.profile.role != 'LE':
        return HttpResponseForbidden("You don't have permission to add warranty cases.")

    if request.method == 'POST':
        form = WarrantyCaseForm(request.POST, user=user, instance=warranty)
        if form.is_valid():
            warranty = form.save()
            return redirect('list_warranty')

    form = WarrantyCaseForm(user=user, instance=warranty)
    return render(
        request,
        'warranty/edit.html',
        {
            'form': form,
            'is_new': is_new,
            'company_name': company_name,
            'section': 'warranty',
            'is_lessor': request.user.profile.role == 'LR',
        }
    )


@login_required
def view_warranty(request, pk):
    warranty = get_object_or_404(WarrantyCase, pk=pk)
    user = request.user
    is_seller = user.profile.role == 'SE'
    company_name = user.profile.display_name

    if request.method == 'POST' and is_seller:
        if warranty.resolved == 'CR':
            warranty.resolved = 'IW'
        elif warranty.resolved == 'IW':
            warranty.resolved = 'CO'
        warranty.save()
        return redirect('view_warranty', pk=warranty.pk)

    return render(
        request,
        'warranty/view.html',
        {
                'warranty': warranty,
                'is_seller': is_seller,
                'company_name': company_name,
                'section': 'warranty',
                'is_lessor': request.user.profile.role == 'LR',
            }
        )


@login_required
def request_paid_list(request):
    payments = Payment.objects.filter(request_paid=True)
    return render(
        request,
        'payment/request_paid_list.html',
        {
            'payments': payments,
            'section': 'requested_payments',
            'is_lessor': request.user.profile.role == 'LR',
        }
    )


@login_required
def request_payment(request, pk):
    payment = get_object_or_404(Payment, pk=pk)

    if not payment.paid and not payment.request_paid:
        payment.request_paid = True
        payment.save()

    return redirect('view_payments', pk=payment.contract.pk)

leasing/templates/warranty/edit.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}
{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">
        {% if is_new %}Добавить гарантийный случай{% else %}Редактировать гарантийный случай{% endif %}
    </h2>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_contract" class="form-label">Контракт</label>
            {{ form.contract }}
        </div>
        <div class="mb-3">
            <label for="id_description" class="form-label">Описание</label>
            {{ form.description }}
        </div>

        <button type="submit" class="btn btn-primary">
            Сохранить
        </button>
        <a href="{% url 'list_warranty' %}" class="btn btn-secondary">Отменить</a>
    </form>
</div>
{% endblock %}

leasing/templates/warranty/list.html
{% extends 'base.html' %}

{% block title %}
	Гарантийные случаи
{% endblock %}

{% block content %}
	<div class="container mt-4">
        {% if warranties %}
        	<h2 class="mb-4">Гарантийные случаи</h2>
        {% else %}
            <h2 class="mb-4">Гарантийные случаи с участием {{ company_name }}</h2>
        {% endif %}

        <!-- Add New Warranty Case Button (Visible to Lessees) -->
        {% if is_lessee %}
        <div class="mb-3">
            <a href="{% url 'add_warranty' %}" class="btn btn-primary">Добавить гарантийный случай</a>
        </div>
        {% endif %}

        <!-- Warranty Cases Table -->
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <thead class="table-primary">
                    <tr>
                        <th>#</th>
                        <th>Контракт</th>
                        <th>Описание</th>
                        <th>Статус</th>
                        <th>Дата создания</th>
                        <th>Действия</th>
                    </tr>
                </thead>
                <tbody>
                    {% for warranty in warranties %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ warranty.contract }}</td>
                            <td>{{ warranty.description }}</td>
                            <td>
                                {% if warranty.resolved == 'CR' %}
                                    <span class="badge bg-secondary">Создан</span>
                                {% elif warranty.resolved == 'IW' %}
                                    <span class="badge bg-warning text-dark">В процессе</span>
                                {% elif warranty.resolved == 'CO' %}
                                    <span class="badge bg-success">Решен</span>
                                {% endif %}
                            </td>
                            <td>{{ warranty.created|date:"d.m.Y" }}</td>
                            <td>
                                <a href="{% url 'view_warranty' warranty.id %}" class="btn btn-sm btn-warning">Открыть</a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="6" class="text-center">Нет доступных гарантийных случаев.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

leasing/templates/warranty/view.html
{% extends 'base.html' %}

{% block content %}
	<div class="container mt-4">
        <h2>Гарантийный случай</h2>
        <div class="card mb-4">
            <div class="card-body">
                <h5 class="card-title">Контракт: {{ warranty.contract }}</h5>
                <p><strong>Описание:</strong> {{ warranty.description }}</p>
                <p><strong>Статус:</strong> 
                    {% if warranty.resolved == 'CR' %}
                        Создан
                    {% elif warranty.resolved == 'IW' %}
                        В работе
                    {% elif warranty.resolved == 'CO' %}
                        Завершен
                    {% endif %}
                </p>
                <p><strong>Дата создания:</strong> {{ warranty.created|date:"d.m.Y" }}</p>
            </div>
        </div>
    
        {% if is_seller %}
        <form method="post">
            {% csrf_token %}
            {% if warranty.resolved == 'CR' %}
                <button type="submit" class="btn btn-warning">Пометить как "В работе"</button>
            {% elif warranty.resolved == 'IW' %}
                <button type="submit" class="btn btn-success">Пометить как "Завершен"</button>
            {% endif %}
        </form>
        {% endif %}
    
        <a href="{% url 'list_warranty' %}" class="btn btn-secondary mt-3">Вернуться</a>
    </div>
{% endblock %}